[package]
name = "my_flet_app"
version = "4.0"
authors = ["Self Fun"]

[build]
targets = ["x86_64-pc-windows-msvc"]
python_version = "3.10"

[dist]
compression = "none"
output_format = "standalone"

[[files]]
path = "assets/"
type = "copy"

[[files]]
path = "ffmpeg/"
type = "copy"

[[files]]
path = "vlc/"
type = "copy"

[[files]]
path = "main.py"
type = "embed"

[[files]]
path = "app_icon.ico"
type = "copy"
